# Generated by Django 3.2.7 on 2022-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220318_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(upload_to='profileimg'),
        ),
    ]
