# Generated by Django 3.2.7 on 2022-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_signup_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
    ]
