# Generated by Django 3.2.7 on 2022-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220319_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(upload_to='profileimg'),
        ),
    ]
