# Generated by Django 3.2.7 on 2022-03-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220320_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
