# Generated by Django 3.2.7 on 2022-03-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='postimg/')),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Covid-19', 'Covid-19'), ('Heart Disease', 'Heart Disease'), ('Immune system', 'Immune System')], max_length=100)),
                ('content', models.TextField(max_length=400)),
                ('summary', models.CharField(max_length=300)),
            ],
        ),
    ]
